site_name: Biblioteca Docs
nav:
  - Inicio: index.md
  - Configuración:
      - Base de Datos: configuracion/base-datos.md
      - Tecnologías: configuracion/tecnologias.md
  - Implementación:
      - Catalogo: implementacion/catalogo.md
      - Usuario: implementacion/usuario.md
      - Prestamo: implementacion/prestamo.md
      - Frontend: implementacion/frontend.md
      - Funciones Automatizadas: implementacion/faas.md
  - Despliegue:
      - Docker Compose: despliegue/docker-compose.md
      - MkDocs: despliegue/mkdocs.md
  - Capturas: capturas.md
  - Pruebas:
      - Plan de pruebas: tests/plan-pruebas.md
      - Informe QA: tests/informe-qa.md
      - MARC 21: tests/informe-marc21.md
theme:
  name: material
  custom_dir: overrides
  language: es
  font:
    text: Reboto
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.highlight
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  # - pdf-export

repo_name: Biblioteca digital
repo_url: https://github.com/anderVZ03/biblioteca-digital.git
