site_name: Biblioteca Docs
nav:
  - Inicio: index.md
  - Configuración:
      - Base de Datos: configuracion/base-datos.md
      - Tecnologías: configuracion/tecnologias.md
  - Implementación:
      - Catalogo: implementacion/catalogo.md
      - Usuario: implementacion/usuario.md
      - Prestamo: implementacion/prestamo.md
      - Frontend: implementacion/frontend.md
      - Funciones Automatizadas: implementacion/faas.md
  - Despliegue:
      - Docker Compose: despliegue/docker-compose.md
      - MkDocs: despliegue/mkdocs.md
theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.highlight
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji

extra_css:
  - stylesheets/extra.css